[package]
name = "laser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.83.0"
ndarray = "0.15.6"
serialport = "4.2.1"

